### ISSUE TITLE
the performance optimization suggestion

### ISSUE THREAD

**Issue by snowyu** [medikoo/lru-queue#1]
1. the map object slow down performance about -200%
   - [setting map in index.js](/medikoo/lru-queue/blob/master/index.js#L14)
2. separate the `add` and `use` operations from `hit` can get more performance
3. only adjust `_lru` and `_mru` index after deleting. It  can increase the `get` operation performance a little. slowdown the delete operation. but the `get` operation is a higher frequency operation than `delete`.

here is my implementation: https://github.com/snowyu/node-secondary-cache/blob/master/src/lru-queue.coffee, It's not a common pretty solution for any type id(use the any type id will slowdown performance too, see `hit`) and it's coffee-script implementation. so I have not PR.

**Comment by medikoo** [comment]
@snowyu great thanks for suggestions, I'm always open for and curious about eventual performance gains I can achieve.

Still, I've looked into your example, and in your code I don't see anything much different from what `lru-queue` actually does. I've even setup a [test case](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd) to compare both solutions, and they perform relatively same.
I get around 3.5s for `lru-queue` and around 3.3s for your version, small gain might be attributed to fact you use actual prototype and instances (V8 optimizes such code better). Still it's nothing close to 200% gain you state.

>  the map object slow down performance about -200%

This is mandatory for algorithm to work properly, and exactly same [map object](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd#file-snowy-lru-queue-js-L69) is created on your side. In your version it seems even heavier as additionally `QueueItem` objects are created, which is not case in `lru-queue`

> separate the add and use operations from hit can get more performance

I don't see how it would help, as anyway code needs to go through `hit` function, and anyway you need [to `add` or to `use`](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd#file-snowy-lru-queue-
js-L74-L83) condition

> only adjust _lru and _mru index after deleting. It can increase the get operation performance a little. slowdown the delete operation. but the get operation is a higher frequency operation than delete.

Your algorithm adjusts those values exactly at same point as mine. I don't see any difference, and don't see a room for improvement here.

Please let me know if I miss something :)

**Comment by snowyu** [comment]
Sorry, maybe I did not express clearly. The `hit` method does not improve any performance, just to unit test compatibility. The performance improvement methods are `"add/push"` and `"use"`.
There is a simple way to test:  just remove the `map[id] = nuIndex` line and watch.

Sorry, the "wrong" `hit` method induces you.

**Comment by snowyu** [comment]
more explains:

In my scene to use your LRUQueue:
1. lookup the cache item to get the item
2. **lookup the map again to get lruIndex**
3. **set new lruIndxe to map**

Now 2nd and 3rd are removed for item can store the lruIndex.

**Comment by snowyu** [comment]
In fact the Doubly-linked list may be the better way for LRUQueue class.

the simple-lur-cache use doubly-linked list.

``````
┌───────────────────────┬────────┬────────┬────────┬────────┬───────┐
│ Time Cost(ms)         │ add    │ update │ get    │ del    │ clear │
├───────────────────────┼────────┼────────┼────────┼────────┼───────┤
│ Fixed Cache(seconday) │ 14.007 │ 5.982  │ 2.784  │ 11.420 │ 0.116 │
├───────────────────────┼────────┼────────┼────────┼────────┼───────┤
│ LRU Cache(seconday)   │ 20.426 │ 13.729 │ 11.332 │ 28.606 │ 0.035 │
├───────────────────────┼────────┼────────┼────────┼────────┼───────┤
│ lru-cache             │ 23.985 │ 15.621 │ 15.752 │ 15.438 │ 0.125 │
├───────────────────────┼────────┼────────┼────────┼────────┼───────┤
│ simple-lru-cache      │ 27.225 │ 6.281  │ 4.886  │ 7.287  │ 0.030 │
└───────────────────────┴────────┴────────┴────────┴────────┴───────┘```

see [node-bench-cache](https://github.com/snowyu/node-bench-cache)
``````

**Comment by medikoo** [comment]
@snowyu thanks for further explanation

> There is a simple way to test: just remove the map[id] = nuIndex line and watch.

To my understanding If we remove `hit` from implementation and just leave `add` and `use`, then `hit` logic will need to be anyway placed in consumer of `lru-queue`. It's exactly same case with your version. You can remove `hit` but then consumer of your utility will need on its own maintain `map` object and generate `QueueItem` objects so queue actually works properly. So after all It doesn't bring any performance gain.

If you still feel it's otherwise, can you fork and update that fibonacci lru [test case](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd), and on basis of that example demonstrate gain that can be achieved? I think using simple real world use case, would be best to demonstrate what you want to prove.

> In my scene to use your LRUQueue:
> 1. lookup the cache item to get the item
> 2. lookup the map again to get lruIndex
> 3. set new lruIndxe to map
> 
> Now 2nd and 3rd are removed for item can store the lruIndex.

If I read correctly, same happens in your version, just 2 is ["lookup the map to get lruIndex"](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd#file-snowyu-lru-queue-js-L64), and 3 is  ["set new lruIndex to item"](https://gist.github.com/medikoo/c3c5779d71f6a8d328fd#file-snowyu-lru-queue-js-L54). Surely you may say, that some of that shouldn't be part of a logic of _lru-queue_, but that logic will anyway need to be done somewhere so _lru-queue_ can be used effectively. Again I don't see where it can bring performance gain.

**Comment by snowyu** [comment]
en, if your main scene is using number, you are right It's the same: we need create a map object to hold it.
But in the database cache scene, the item is object and already exists. so no need to create an object to wrap it.

**Comment by medikoo** [comment]
> But in the database cache scene, the item is object and already exists. so no need to create an object to wrap it.

So in that case you modify totally foreign object, it breaks encapsulation which can be error-prone, I don't think it's wise approach. Justifiable might be to use WeakMap instead, but again, it may work only for object values, while `lru-queue` stands on fact that you pass _string_ ids. It's use case agnostic, cached values can be anything not necessary objects.

**Comment by snowyu** [comment]
Yes, as general LRUQueue it is a problem. so No PR, just suggestion only :) .
WeakMap may be a simple perfect solution for object, but it's es6 only and it can not suite the scene: the cache wanna hold the object to avoid gc. 

as general LRUQueue may be have a way to let user decide to use map or not. I have no idea.

btw, i wonder why not use the object property to write code? it is more clear to read. and seems no performance lost.

``` coffee
module.exports = LRUQueue = (limit)->
   size = 0
   hit: (id)->
   delete: del = (id)->

module.exports = class LRUQueue
   constructor: (@limit)->
      return new LRUQueue(limit) if this not instanceof LRUQueue
      @size = 0
   hit: (id)->
   delete: del = (id)->

```

**Comment by medikoo** [comment]
> btw, i wonder why not use the object property to write code? it is more clear to read. and seems no performance lost.

If I understand correctly at this point _lru-queue_ does exactly that.
Still moving it to real constructor and instances (so class-like), may improve performance a bit. At least V8 does special optimizations for such definitions.

**Comment by medikoo** [comment]
And getting back to perfomance, I know that [lru-cache](https://github.com/isaacs/node-lru-cache), performs really well.
See: https://github.com/medikoo/memoize#benchmarks it's based on this [benchmark](https://github.com/medikoo/memoize/blob/master/benchmark/fibonacci.js)
 I haven't yet investigated why this one gets significantly better result (34ms vs 94ms for memoization based on _lru-queue_), but it might be there's some things in _memoizee_ itself that put it down.

**Comment by snowyu** [comment]
Aha, you have a right way now. I have investigated it: 

First I used your lru-queue and I had found the performance issue compare with lru-cache. about two times slower. I located the `map` and fixed after comparison the code . But it had been still slower than lru-cache, so I had separated the `hit` to `add` and `use`.  And now it is a little faster than lru-cache except deletion operation. 

I just replace the `lru-cache` to mine in your benchmarks:

``` js
var
  , lruCache   = require('secondary-cache/lib/lru-cache')
//  , lruCache   = require('lru-cache')
```

And the result on my machine:

``` bash
Fibonacci 3000 x10:

1:    16ms  lru-cache                 LRU (max: 1000)
2:    30ms  Underscore
3:    35ms  Memoizee (primitive mode)
4:    96ms  Lo-dash
5:   116ms  Memoizee (primitive mode) LRU (max: 1000)
6:   265ms  Memoizee (object mode)    LRU (max: 1000)
7:   304ms  Memoizee (object mode)
```

**Comment by snowyu** [comment]
sorry, it should change this line too:

``` js
  //lruObj = lruCache({ max: lruMax });
  lruObj = lruCache(lruMax);
```

now the result is:

``` bash
Fibonacci 3000 x10:

1:    25ms  Underscore
2:    37ms  Memoizee (primitive mode)
3:    41ms  lru-cache                 LRU (max: 1000)
4:    69ms  Lo-dash
5:   111ms  Memoizee (primitive mode) LRU (max: 1000)
6:   266ms  Memoizee (object mode)    LRU (max: 1000)
7:   326ms  Memoizee (object mode)
```

**Comment by snowyu** [comment]
I have PR on memoize, add the new secondary lru-cache to benchmark. I like the memoize idea. But the code is not easy to read.

>    Still moving it to real constructor and instances (so class-like),

good news.  maybe memoize  too?
