### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fazouane-marouane** [medikoo/lru-queue#2]
Hello,

It took me some time to test a few optimisation to this lib (cf https://github.com/medikoo/memoizee/issues/73#issuecomment-424322724 )

There are a few performance issues that you can see on the following test cases (see my PR). The alternative implementations that tested are 1/ linked list version 2/ a queue based on a `Set`.

>----randomInsert----
Old implementation -> 58330.030482023954ms
Current implementation -> **9830.84556800127ms**
Linked list implementation -> 13721.152534008026ms
----incrementInsert----
Old implementation -> 37336.09836298227ms
Current implementation -> **1679.1123040020466ms**
Linked list implementation -> 3033.5687620043755ms
----frequentHit----
Old implementation -> 41213.18298500776ms
Current implementation -> **1209.5061120092869ms**
Linked list implementation -> 3324.8530479967594ms
----cyclical----
Old implementation -> 36146.50369602442ms
Current implementation -> **6161.038066983223ms**
Linked list implementation -> 11958.172848016024ms
----fibo_5----
Old implementation -> 2851.7648769915104ms
Current implementation -> **1385.3255870044231ms**
Linked list implementation -> 1247.3645560145378ms
----fibo_1000----
Old implementation -> 1848.6322599947453ms
Current implementation -> **2150.804029017687ms**
Linked list implementation -> 1251.7856360077858ms

In all the test cases except for the last one there's a significant speedup (respectively, 5x 22x 34x 5x 2x and 0.86x).

I added the code of the benchmark to the PR too. @medikoo Do you have some thoughts on this?

**Comment by medikoo** [comment]
Thank you @fazouane-marouane I will look into that now
